name: online_shop
description: A new Flutter project.
publish_to: 'none'
# Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.8
  shimmer: ^3.0.0
  firebase_remote_config: ^3.0.15
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_messaging: ^14.6.9
  firebase_analytics: ^10.5.1
  flutter_local_notifications: ^17.0.0
  get: ^4.6.5
  intl: ^0.18.0
  permission_handler: ^11.0.1
  percent_indicator: ^4.2.3
  material_dialogs: ^1.1.4
  lottie: ^2.6.0
  velocity_x: ^4.1.1
  google_fonts: ^6.2.0
  eva_icons_flutter: ^3.1.0
  like_button: ^2.0.5
  flutter_svg: ^2.0.10+1
  injectable: ^2.3.2
  get_it: ^7.6.7
  order_tracker: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  dio: ^5.4.1
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - asset/images/
     - asset/svg/


  fonts:
     - family: Gilroy
       fonts:
         - asset: asset/fonts/Gilroy-Thin.ttf
           weight: 100
         - asset: asset/fonts/Gilroy-ThinItalic.ttf
           weight: 100
           style: italic
         - asset: asset/fonts/Gilroy-UltraLight.ttf
           weight: 200
         - asset: asset/fonts/Gilroy-UltraLightItalic.ttf
           weight: 200
           style: italic
         - asset: asset/fonts/Gilroy-Light.ttf
           weight: 300
         - asset: asset/fonts/Gilroy-LightItalic.ttf
           weight: 300
           style: italic

         - asset: asset/fonts/Gilroy-Medium.ttf
           weight: 500
         - asset: asset/fonts/Gilroy-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: asset/fonts/Gilroy-SemiBold.ttf
           weight: 600
         - asset: asset/fonts/Gilroy-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: asset/fonts/Gilroy-Bold.ttf
           weight: 700
         - asset: asset/fonts/Gilroy-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: asset/fonts/Gilroy-ExtraBold.ttf
           weight: 800
         - asset: asset/fonts/Gilroy-ExtraBoldItalic.ttf
           weight: 800
           style: italic
         - asset: asset/fonts/Gilroy-Black.ttf
           weight: 900
         - asset: asset/fonts/Gilroy-BlackItalic.ttf
           weight: 900
           style: italic
         - asset: asset/fonts/Gilroy-Heavy.ttf
           weight: 900
