name: online_shop
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - asset/images/


  fonts:
     - family: Gilroy
       fonts:
         - asset: asset/fonts/Gilroy-Thin.ttf
           weight: 100
         - asset: asset/fonts/Gilroy-ThinItalic.ttf
           weight: 100
           style: italic
         - asset: asset/fonts/Gilroy-UltraLight.ttf
           weight: 200
         - asset: asset/fonts/Gilroy-UltraLightItalic.ttf
           weight: 200
           style: italic
         - asset: asset/fonts/Gilroy-Light.ttf
           weight: 300
         - asset: asset/fonts/Gilroy-LightItalic.ttf
           weight: 300
           style: italic

         - asset: asset/fonts/Gilroy-Medium.ttf
           weight: 500
         - asset: asset/fonts/Gilroy-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: asset/fonts/Gilroy-SemiBold.ttf
           weight: 600
         - asset: asset/fonts/Gilroy-SemiBoldItalic.ttf
           weight: 600
           style: italic
         - asset: asset/fonts/Gilroy-Bold.ttf
           weight: 700
         - asset: asset/fonts/Gilroy-BoldItalic.ttf
           weight: 700
           style: italic
         - asset: asset/fonts/Gilroy-ExtraBold.ttf
           weight: 800
         - asset: asset/fonts/Gilroy-ExtraBoldItalic.ttf
           weight: 800
           style: italic
         - asset: asset/fonts/Gilroy-Black.ttf
           weight: 900
         - asset: asset/fonts/Gilroy-BlackItalic.ttf
           weight: 900
           style: italic
         - asset: asset/fonts/Gilroy-Heavy.ttf
           weight: 900
